// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(` 
  STARTUP

  SET_ACTIVE_DRAWER_ITEM

  SET_LAST_VISITED_ROUTE
  RESET_LAST_VISITED_ROUTE

  LOGIN
  LOGOUT

  SET_USER
  CLEAR_USER
  SET_REMEMBER_USER

  NETWORK_SUCCESS
  NETWORK_FAILURE

  SET_ATTACHED_FILES
  CLEAR_ATTACHED_FILES

  UPDATE_DEVICE_DIMENSIONS

  UPDATE_USERS_SCREEN
  UPDATE_USER_SCREEN

  UPDATE_JOBS_SCREEN
  UPDATE_JOB_SCREEN

  UPDATE_ORGANIZATIONS_SCREEN
  UPDATE_ORGANIZATION_SCREEN

  UPDATE_APPOINTMENTS_SCREEN
  UPDATE_APPOINTMENT_SCREEN
`)